# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: django-deployment
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: django-app
#   template:
#     metadata:
#       labels:
#         app: django-app
#     spec:
#       initContainers:
#       - name: init-db
#         image: amitpatidar587/lyvup:05  # Same as your Django app image
#         command:
#         - /bin/sh
#         - -c
#         - |
#           python manage.py makemigrations
#           python manage.py migrate
#         env:
#         - name: DB_NAME
#           value: "postgres"
#         - name: DB_USER
#           value: "postgres"
#         - name: DB_PASSWORD
#           value: "postgres123"
#         - name: DB_HOST
#           value: "postgres-service"
#         - name: DB_PORT
#           value: "5432"
#       containers:
#       - name: django-contain
#         image: amitpatidar587/lyvup:05  # Your Django application image
#         ports:
#         - containerPort: 8000
#         env:
#         - name: DB_NAME
#           value: "postgres"
#         - name: DB_USER
#           value: "postgres"
#         - name: DB_PASSWORD
#           value: "postgres123"
#         - name: DB_HOST
#           value: "postgres-service"
#         - name: DB_PORT
#           value: "5432"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: django-service
# spec:
#   selector:
#     app: django-app
#   ports:
#     - name: http
#       port: 8000
#       targetPort: 8000
#   type: LoadBalancer
